### PR TITLE
added linkedin-automation... 

### PR DESCRIPTION
**Pull request by rohan2734**
...to send conneciton requests with messages to a list of users using python,selenium, and beautifulsoap4

### CODE REVIEW

**Review by adityaarakeri — CHANGES_REQUESTED** [review]
Please do not add `.exe` files to your PR. have a pre install script to add it if needed.

**Comment by rohan2734** [comment]
> Please do not add `.exe` files to your PR. have a pre install script to add it if needed.

what is preinstall script?, otherwise shall I delete that .exe file?

**Comment by adityaarakeri** [comment]
delete the `.exe` file and resolve the merge conflicts

**Comment by rohan2734** [comment]
@adityaarakeri now there are no conflicts sir. you can check.

**Pull request merged**
